-- 퍼즐 도감: 엑셀 정보와 WebP 이미지가 모두 매칭된 90개
-- 실행 전: MySQL 8.0, --default-character-set=utf8mb4 권장
-- 제외: 엑셀 도감순 57~58(일화), 83~98(시즌 한정) - 현재 이미지 없음

CREATE TABLE IF NOT EXISTS puzzle_collections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_id INT NOT NULL UNIQUE COMMENT 'TheGamer 원본 퍼즐 이미지 번호',
    catalog_order INT NOT NULL UNIQUE COMMENT '게임 내 도감순',
    category VARCHAR(50) NOT NULL COMMENT '일반/동물/이벤트명',
    name VARCHAR(100) NOT NULL UNIQUE COMMENT '한국어 퍼즐 이름',
    english_name VARCHAR(150) NULL COMMENT '이미지 대조용 영문 이름',
    size VARCHAR(20) NOT NULL COMMENT '1x1~4x4',
    acquisition_method VARCHAR(150) NOT NULL COMMENT '획득 방법',
    purchase_price VARCHAR(50) NULL COMMENT '구매 가격 원문',
    image_url VARCHAR(255) NOT NULL COMMENT 'WebP 이미지 경로',
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_puzzle_category (category),
    INDEX idx_puzzle_size (size),
    INDEX idx_puzzle_sort_order (sort_order)
);

INSERT INTO puzzle_collections (
    image_id, catalog_order, category, name, english_name, size,
    acquisition_method, purchase_price, image_url, sort_order
) VALUES
    (1, 1, '일반', '시청', 'Town Hall', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/001_시청.webp', 1),
    (2, 2, '일반', '예술의 거리 (밤)', 'Art Street Entrance', '1x1', '꿈-퍼즐', NULL, '/images/others/puzzles/002_예술의 거리 (밤).webp', 2),
    (3, 3, '일반', '옷가게 앞', 'Clothing Store Front', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/003_옷가게 앞.webp', 3),
    (4, 4, '일반', '산수 오두막', 'Mountain Spring Cottage', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/004_산수 오두막.webp', 4),
    (5, 5, '일반', '맑은 빛 섬', 'Sunlit Island', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/005_맑은 빛 섬.webp', 5),
    (6, 6, '일반', '어촌 전망', 'Fishing Village Vista', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/006_어촌 전망.webp', 6),
    (7, 7, '일반', '고래산 풍경', 'Whale Mountain', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/007_고래산 풍경.webp', 7),
    (8, 8, '일반', '열기구', 'Hot Air Balloon', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/008_열기구.webp', 8),
    (9, 9, '일반', '해변 등대', 'Seaside Lighthouse', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/009_해변 등대.webp', 9),
    (10, 10, '일반', '고래 분수', 'Whale Fountain', '1x1', '잡화점,버블', NULL, '/images/others/puzzles/010_고래 분수.webp', 10),
    (11, 11, '동물', '판다 탐험', 'Traveling Panda', '1x1', '친밀도선물-판다', NULL, '/images/others/puzzles/011_판다 탐험.webp', 11),
    (12, 12, '동물', '카피바라 휴식', 'Relaxed Capybara', '1x1', '친밀도선물-카피바라', NULL, '/images/others/puzzles/012_카피바라 휴식.webp', 12),
    (13, 13, '동물', '귀여운 토끼와 차', 'Bunny''s Tea Time', '1x1', '친밀도선물-토끼', NULL, '/images/others/puzzles/013_귀여운 토끼와 차.webp', 13),
    (14, 14, '동물', '고래산의 여우', 'Fox of Whale Mountain', '1x1', '친밀도선물-여우', NULL, '/images/others/puzzles/014_고래산의 여우.webp', 14),
    (15, 15, '동물', '해달과 물고기', 'Sea Otter''s Watch', '1x1', '친밀도선물-해달', NULL, '/images/others/puzzles/015_해달과 물고기.webp', 15),
    (16, 16, '동물', '담비의 미소', 'Ferret''s Merry Moment', '1x1', '친밀도선물-담비', NULL, '/images/others/puzzles/016_담비의 미소.webp', 16),
    (17, 17, '동물', '순록의 산책', 'Strolling Deer', '1x1', '친밀도선물-순록', NULL, '/images/others/puzzles/017_순록의 산책.webp', 17),
    (18, 18, '동물', '알파카와 밤', 'Alpaca & Night', '1x1', '친밀도선물-알파카', NULL, '/images/others/puzzles/018_알파카와 밤.webp', 18),
    (19, 19, '일반', '예술의 거리 (낮)', 'Art Street Center', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/019_예술의 거리 (낮).webp', 19),
    (20, 20, '일반', '서점 한 구석', 'Bookstall Corner', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/020_서점 한 구석.webp', 20),
    (21, 21, '일반', '거주 거리 입구', 'Residential Street Entrance', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/021_거주 거리 입구.webp', 21),
    (22, 22, '일반', '여유로운 시간', 'Leisure Time', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/022_여유로운 시간.webp', 22),
    (23, 23, '일반', '보름달 밤', 'Full Moon Night', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/023_보름달 밤.webp', 23),
    (24, 24, '일반', '풍차꽃밭', 'Windmill Flower Field', '2x2', '꿈-퍼즐', NULL, '/images/others/puzzles/024_풍차꽃밭.webp', 24),
    (25, 25, '일반', '그 자리 도토리', 'Oak-Oak', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/025_그 자리 도토리.webp', 25),
    (26, 26, '일반', '어촌 광장', 'Fishing Village Square', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/026_어촌 광장.webp', 26),
    (27, 27, '일반', '화원 정자', 'Garden Pavilion', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/027_화원 정자.webp', 27),
    (28, 28, '일반', '꽥꽥이 점핑', 'Yellow Duck Jump Puzzle', '2x2', '잡화점,버블', NULL, '/images/others/puzzles/028_꽥꽥이 점핑.webp', 28),
    (29, 29, '동물', '판다와 대나무', 'Pandas & Bamboo', '2x2', '친밀도선물-판다', NULL, '/images/others/puzzles/029_판다와 대나무.webp', 29),
    (30, 30, '동물', '콩콩 카피바라', 'Bumping Capybaras', '2x2', '친밀도선물-카피바라', NULL, '/images/others/puzzles/030_콩콩 카피바라.webp', 30),
    (31, 31, '동물', '함께하는 토끼', 'Bunny Friends', '2x2', '친밀도선물-토끼', NULL, '/images/others/puzzles/031_함께하는 토끼.webp', 31),
    (32, 32, '동물', '여우의 여행', 'Roaming Fox', '2x2', '친밀도선물-여우', NULL, '/images/others/puzzles/032_여우의 여행.webp', 32),
    (33, 33, '동물', '장난치는 수달', 'Playful Sea Otters', '2x2', '친밀도선물-해달', NULL, '/images/others/puzzles/033_장난치는 수달.webp', 33),
    (34, 34, '동물', '먹이를 찾는 담비', 'Foraging Ferret', '2x2', '친밀도선물-담비', NULL, '/images/others/puzzles/034_먹이를 찾는 담비.webp', 34),
    (35, 35, '동물', '순록과 함께', 'Adult & Young Deer', '2x2', '친밀도선물-순록', NULL, '/images/others/puzzles/035_순록과 함께.webp', 35),
    (36, 36, '동물', '알파카의 집', 'Alpaca Family', '2x2', '친밀도선물-알파카', NULL, '/images/others/puzzles/036_알파카의 집.webp', 36),
    (37, 37, '일반', '덩굴과 함께', 'Heart Hedge', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/037_덩굴과 함께.webp', 37),
    (38, 38, '일반', '카페', 'Cozy Cafe', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/038_카페.webp', 38),
    (39, 39, '일반', '어촌 분수', 'Fishing Village Fountain', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/039_어촌 분수.webp', 39),
    (40, 40, '일반', '숲속 시냇물', 'Forest Stream', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/040_숲속 시냇물.webp', 40),
    (41, 41, '일반', '해변 놀이', 'Beach Fun', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/041_해변 놀이.webp', 41),
    (42, 42, '일반', '온천산 호수', 'Onsen Mountain Lake', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/042_온천산 호수.webp', 42),
    (43, 43, '일반', '숲속의 밤', 'Woodland Night Camping', '3x3', '꿈-퍼즐', NULL, '/images/others/puzzles/043_숲속의 밤.webp', 43),
    (44, 44, '일반', '어선의 여유', 'Leisurely Fishing Boat', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/044_어선의 여유.webp', 44),
    (45, 45, '일반', '미스터리 파티', 'Eerie Party', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/045_미스터리 파티.webp', 45),
    (46, 46, '일반', '스프링 추억', 'Spring Festival Memory', '3x3', '잡화점,버블', NULL, '/images/others/puzzles/046_스프링 추억.webp', 46),
    (47, 47, '일반', '거주 거리', 'Residential Street Corner', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/047_거주 거리.webp', 47),
    (48, 48, '일반', '피아노 선율', 'Piano Melodies', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/048_피아노 선율.webp', 48),
    (49, 49, '일반', '불꽃놀이', 'Fireworks Festival', '4x4', '꿈-퍼즐', NULL, '/images/others/puzzles/049_불꽃놀이.webp', 49),
    (50, 50, '일반', '캠핑의 즐거움', 'Camp Fun', '4x4', '꿈-퍼즐', NULL, '/images/others/puzzles/050_캠핑의 즐거움.webp', 50),
    (51, 51, '일반', '카피바라 석상', 'Capybara Statues', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/051_카피바라 석상.webp', 51),
    (52, 52, '일반', '기차행렬', 'Parking Lot', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/052_기차행렬.webp', 52),
    (53, 53, '일반', '숲속 다리', 'Forest Suspension Bridge', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/053_숲속 다리.webp', 53),
    (54, 54, '일반', '교외 주차장', 'Suburbs Parking', '4x4', '잡화점,버블', '80별', '/images/others/puzzles/054_교외 주차장.webp', 54),
    (55, 55, '일반', '고래와 구름', 'Whale Cloud', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/055_고래와 구름.webp', 55),
    (56, 56, '일반', '푸른하늘 야자수', 'Coconut Trees Under Sky', '4x4', '잡화점,버블', NULL, '/images/others/puzzles/056_푸른하늘 야자수.webp', 56),
    (57, 59, '동물', '판다 홀로 앉기', 'Solitary Panda', '3x3', '친밀도선물-판다', NULL, '/images/others/puzzles/057_판다 홀로 앉기.webp', 57),
    (58, 60, '동물', '판다와 함께 성장', 'Growing With Bears', '2x2', '친밀도선물-판다', NULL, '/images/others/puzzles/058_판다와 함께 성장.webp', 58),
    (59, 61, '동물', '판다 가족', 'Panda Family', '4x4', '친밀도선물-판다', NULL, '/images/others/puzzles/059_판다 가족.webp', 59),
    (60, 62, '동물', '카피바라 산', 'Capybara Mountain', '4x4', '친밀도선물-카피바라', NULL, '/images/others/puzzles/060_카피바라 산.webp', 60),
    (61, 63, '동물', '좁은 길의 만남', 'Crossing Paths', '3x3', '친밀도선물-카피바라', NULL, '/images/others/puzzles/061_좁은 길의 만남.webp', 61),
    (62, 64, '동물', '카피바라 회식', 'Capybara Reunion', '2x2', '친밀도선물-카피바라', NULL, '/images/others/puzzles/062_카피바라 회식.webp', 62),
    (63, 65, '동물', '장난꾸러기 토끼', 'Naughty Bunny', '2x2', '친밀도선물-토끼', NULL, '/images/others/puzzles/063_장난꾸러기 토끼.webp', 63),
    (64, 66, '동물', '토끼 기다림', 'Bookworm Bunny', '3x3', '친밀도선물-토끼', NULL, '/images/others/puzzles/064_토끼 기다림.webp', 64),
    (65, 67, '동물', '나란히 앉은 토끼', 'Bunny in a Row', '4x4', '친밀도선물-토끼', NULL, '/images/others/puzzles/065_나란히 앉은 토끼.webp', 65),
    (66, 68, '동물', '아기여우 캠핑', 'Fox Camping', '3x3', '친밀도선물-여우', NULL, '/images/others/puzzles/066_아기여우 캠핑.webp', 66),
    (67, 69, '동물', '늦은 여우들', 'Latecoming Fox', '2x2', '친밀도선물-여우', NULL, '/images/others/puzzles/067_늦은 여우들.webp', 67),
    (68, 70, '동물', '여우들의 꽃구경', 'Foxes Admiring Flowers', '4x4', '친밀도선물-여우', NULL, '/images/others/puzzles/068_여우들의 꽃구경.webp', 68),
    (69, 71, '동물', '나른한 수달', 'Lazy Sea Otter', '3x3', '친밀도선물-해달', NULL, '/images/others/puzzles/069_나른한 수달.webp', 69),
    (70, 72, '동물', '바라보는 해달', 'Sea Otter''s Pier Gaze', '4x4', '친밀도선물-해달', NULL, '/images/others/puzzles/070_바라보는 해달.webp', 70),
    (71, 73, '동물', '해달 둥둥', 'Floating Sea Otter', '2x2', '친밀도선물-해달', NULL, '/images/others/puzzles/071_해달 둥둥.webp', 71),
    (72, 74, '동물', '들보 위 담비', 'Ferret on the Beam', '2x2', '친밀도선물-담비', NULL, '/images/others/puzzles/072_들보 위 담비.webp', 72),
    (73, 75, '동물', '가족 외출', 'Family Outing', '3x3', '친밀도선물-담비', NULL, '/images/others/puzzles/073_가족 외출.webp', 73),
    (74, 76, '동물', '담비 무리의 모임', 'Ferret Gathering', '4x4', '친밀도선물-담비', NULL, '/images/others/puzzles/074_담비 무리의 모임.webp', 74),
    (75, 77, '동물', '순수한 아기 순록', 'Innocent Deer', '4x4', '친밀도선물-순록', NULL, '/images/others/puzzles/075_순수한 아기 순록.webp', 75),
    (76, 78, '동물', '계곡을 거슬러가는 순록', 'Creek-Crossing Deer', '3x3', '친밀도선물-순록', NULL, '/images/others/puzzles/076_계곡을 거슬러가는 순록.webp', 76),
    (77, 79, '동물', '행복한 순록 가족', 'Happy Deer Family', '2x2', '친밀도선물-순록', NULL, '/images/others/puzzles/077_행복한 순록 가족.webp', 77),
    (78, 80, '동물', '따뜻한 햇살 목욕', 'Sunbathing Alpaca', '2x2', '친밀도선물-알파카', NULL, '/images/others/puzzles/078_따뜻한 햇살 목욕.webp', 78),
    (79, 81, '동물', '알파카 산책', 'Alpaca Stroll', '3x3', '친밀도선물-알파카', NULL, '/images/others/puzzles/079_알파카 산책.webp', 79),
    (80, 82, '동물', '알파카 여행', 'Alpaca''s Journey', '4x4', '친밀도선물-알파카', NULL, '/images/others/puzzles/080_알파카 여행.webp', 80),
    (99, 99, '고래 탐사 시즌', '환상 고래낙하', NULL, '4x4', '고래 탐사 시즌-트렌드 상점', '3,760 토큰', '/images/others/puzzles/099_환상 고래낙하.webp', 81),
    (100, 100, '고래 탐사 시즌', '고래낙하 협곡', NULL, '4x4', '고래 탐사 시즌-트렌드 상점', '3,760 토큰', '/images/others/puzzles/100_고래낙하 협곡.webp', 82),
    (101, 101, '고래 탐사 시즌', '장난치는 돌고래', NULL, '3x3', '고래 탐사 시즌-트렌드 상점', '3,760 토큰', '/images/others/puzzles/101_장난치는 돌고래.webp', 83),
    (102, 102, '고래 탐사 시즌', '천연 갤러리', NULL, '3x3', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/102_천연 갤러리.webp', 84),
    (103, 103, '고래 탐사 시즌', '푸른 바다 풍경', NULL, '3x3', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/103_푸른 바다 풍경.webp', 85),
    (104, 104, '고래 탐사 시즌', '유영하는 돌고래', NULL, '2x2', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/104_유영하는 돌고래.webp', 86),
    (105, 105, '고래 탐사 시즌', '흰동가리 친구들', NULL, '2x2', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/105_흰동가리 친구들.webp', 87),
    (106, 106, '고래 탐사 시즌', '해변의 순간', NULL, '2x2', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/106_해변의 순간.webp', 88),
    (107, 107, '고래 탐사 시즌', '숲속의 저녁', NULL, '2x2', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/107_숲속의 저녁.webp', 89),
    (108, 108, '고래 탐사 시즌', '고래 뱃머리', NULL, '2x2', '고래 탐사 시즌-트렌드 상점', '1,200 토큰', '/images/others/puzzles/108_고래 뱃머리.webp', 90) AS new
ON DUPLICATE KEY UPDATE
    catalog_order = new.catalog_order,
    category = new.category,
    name = new.name,
    english_name = new.english_name,
    size = new.size,
    acquisition_method = new.acquisition_method,
    purchase_price = new.purchase_price,
    image_url = new.image_url,
    sort_order = new.sort_order;
