-- Generated from C:\Users\k\Desktop\user_kit\docs\명인 정보
-- Rows marked X are intentionally left NULL so the UI can show disabled mastery state.

-- 명인 fish.txt
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '가다랑어';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '갈치';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '극지연어';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '미노우';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '민물배스';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '바다새우';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '바벨';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '배스';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '백조어';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '붕어';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '왕새우';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '유럽백조어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '유럽참개구리';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '유럽처브';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '정어리';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '텐치';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '노랑촉수';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '대서양은상어';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '돌마자';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '매화농어';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '머드개복치';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '바다가시고기';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '바다빙어';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '노란전갱이';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '소라게';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '아귀';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '올챙이';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '유럽민물가재';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '홍합';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '흰동가리';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '나비잉어';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '대문짝넙치';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '대서양연어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '레드벨리피라냐';
UPDATE fish_collections SET mastery_beginner_max = 150, mastery_intro_min = 150, mastery_expert_min = 450, mastery_master_min = 900 WHERE name = '민물게';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '민물대구';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '유럽가자미';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '유럽잉어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '참문어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '큰입배스';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '대서양고등어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '루드';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '민물베도라치';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '송어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '유럽가재';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '유럽날오징어';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '두툽상어';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '등불성대';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '북어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '사루기';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '첨연어';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '큰진주조개';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '검은점돔';
UPDATE fish_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '둑중개';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '산갈치';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '유럽장어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '줄무늬송사리';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '큰가시고기';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '금붕어';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '북유럽파란가재';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '킹크랩';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '펄고기';
UPDATE fish_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '해덕대구';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '황금 킹크랩';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '강꼬치고기';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '개복치';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '붉은개복치';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '참다랑어';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '펌프킨시드';
UPDATE fish_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '후첸';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '귀상어';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '북극곤들매기';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '블루길';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '유럽메기';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '청상아리';
UPDATE fish_collections SET mastery_beginner_max = 30, mastery_intro_min = 30, mastery_expert_min = 90, mastery_master_min = 180 WHERE name = '황새치';

-- 명인 bug.txt
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '멧노랑나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '배추흰나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '별노린재';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '붉은고리호랑나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '슬코스키몰포나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '아스파라거스벌레';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '아폴로모시나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '오아시스메뚜기';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '유럽갈고리나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '큰고추잠자리';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '호랑나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '넉점박이잠자리';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '녹색호랑풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '말벌호랑하늘소';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '망치다리메뚜기';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '연푸른부전나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '칠성 무당벌레';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '파란꽃풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '호박벌';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '개미';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '긴꼬리산누에나방';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '보라네발나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '분홍색 철써기';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '붉은목제비나비';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '여치';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '홍날개';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '흰점꼬리털벌';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '매미';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '무지개사마귀';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '밀잠자리';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '사성 무당벌레';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '큰줄무늬메뚜기';
UPDATE bug_collections SET mastery_beginner_max = 200, mastery_intro_min = 200, mastery_expert_min = 600, mastery_master_min = 1200 WHERE name = '표범무늬네발나비';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '고산수염하늘소';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '공작나비';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '보라벌';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '신선나비';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '이색무당벌레';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '파푸아사마귀';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '흰마녀밤나방';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '녹색날개호랑나비';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '물잠자리';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '산악사슴벌레';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '은빛보석풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '파란노린재';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '메넬라우스나비';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '보석꽃풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '왕나비';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '찔레잠자리';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '티폰쇠똥구리';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '황금보석풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '이사벨라나방';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '장수풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '피카소노린재';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '혜성꼬리나방';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '무지개사슴벌레';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '악마꽃사마귀';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '진주네발나비';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '황금귀신사슴벌레';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '나선주머니나방';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '헤라클레스풍뎅이';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '헤쿠바몰포나비';
UPDATE bug_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 150, mastery_master_min = 300 WHERE name = '헬레나몰포나비';

-- 명인 bird.txt
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '굴뚝새';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '꼬까울새';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '노랑배박새';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '멋쟁이새';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '분홍가슴비둘기';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '염주비둘기';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '청공작';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '청금강앵무';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '청둥오리';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '큰홍학';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '푸른머리되새';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '동고비';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '바다갈매기';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '빨간머리때까치';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '수염오목눈이';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '웡가비둘기';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '홍머리오리';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '검은턱오목눈이';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '녹자작';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '유럽가마우지';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '유럽꾀꼬리';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '호사북방오리';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '홍금강앵무';
UPDATE bird_collections SET mastery_beginner_max = 400, mastery_intro_min = 400, mastery_expert_min = 1200, mastery_master_min = 2400 WHERE name = '황오리';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '노란머리바우어새';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '솔양진이';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '알락할미새';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '흰비오리';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '노랑배딱새';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '올리브비둘기';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '유럽벌잡이새';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '작은홍학';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '붉은뺨가마우지';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '칡부엉이';
UPDATE bird_collections SET mastery_beginner_max = 240, mastery_intro_min = 240, mastery_expert_min = 720, mastery_master_min = 1440 WHERE name = '콩새';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '푸른박새';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '황조롱이';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '히아신스금강앵무';
UPDATE bird_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '매';
UPDATE bird_collections SET mastery_beginner_max = 180, mastery_intro_min = 180, mastery_expert_min = 540, mastery_master_min = 1080 WHERE name = '분홍비둘기';
UPDATE bird_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '녹공작';
UPDATE bird_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '황제가마우지';
UPDATE bird_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '수리부엉이';
UPDATE bird_collections SET mastery_beginner_max = 100, mastery_intro_min = 100, mastery_expert_min = 300, mastery_master_min = 600 WHERE name = '아조레스멋쟁이새';

-- 명인 cooking.txt
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '검은 트러플 파이';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '구운 그물버섯';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '구운 느타리버섯';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '구운 버섯';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '구운 양송이버섯';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '구운 표고버섯';
UPDATE cooking_collections SET mastery_beginner_max = 15, mastery_intro_min = 15, mastery_expert_min = 45, mastery_master_min = 90 WHERE name = '그린 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '그물버섯 파이';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '느타리버섯 파이';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '딸기 잼';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '라즈베리 잼';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '레드 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '리트리버 카눌레';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '리트리버 콘파나';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '몰티즈 카눌레';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '몰티즈 콘파나';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '믹스 잼';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '버섯 파이';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '베지 샐러드';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '부활절 달걀';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '부활절 보라 달걀';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '부활절 이스터에그 파티';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '부활절 주황 달걀';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '부활절 초록 달걀';
UPDATE cooking_collections SET mastery_beginner_max = 45, mastery_intro_min = 45, mastery_expert_min = 135, mastery_master_min = 270 WHERE name = '블루 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '블루베리 잼';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '사과 잼';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '양송이버섯 파이';
UPDATE cooking_collections SET mastery_beginner_max = 15, mastery_intro_min = 15, mastery_expert_min = 45, mastery_master_min = 90 WHERE name = '옐로우 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '오렌지 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '오렌지 잼';
UPDATE cooking_collections SET mastery_beginner_max = 45, mastery_intro_min = 45, mastery_expert_min = 135, mastery_master_min = 270 WHERE name = '오리지널 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '잔디 케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '초콜릿 소스';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '치즈케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '케첩';
UPDATE cooking_collections SET mastery_beginner_max = 45, mastery_intro_min = 45, mastery_expert_min = 135, mastery_master_min = 270 WHERE name = '퍼플 롤케이크';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '포도 잼';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '표고버섯 파이';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '피시 앤 칩스';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '하트 강아지';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '카페라떼';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '커피';
UPDATE cooking_collections SET mastery_beginner_max = 160, mastery_intro_min = 160, mastery_expert_min = 480, mastery_master_min = 960 WHERE name = '훈제 연어 베이글';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '검은 트러플 크림 파스타';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '씨푸드 덮밥';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '컨트리 스튜';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '미트소스 파스타';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '씨푸드 피자';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '당근 케이크';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '애플파이';
UPDATE cooking_collections SET mastery_beginner_max = 120, mastery_intro_min = 120, mastery_expert_min = 360, mastery_master_min = 720 WHERE name = '콘스프';
UPDATE cooking_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '럭셔리 씨푸드 플래터';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '티라미수';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '잉글리시 애프터눈 티';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '캠핑 세트';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '랍스터 냉채';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '미트버거';
UPDATE cooking_collections SET mastery_beginner_max = 80, mastery_intro_min = 80, mastery_expert_min = 240, mastery_master_min = 480 WHERE name = '북유럽파란가재 냉채';
UPDATE cooking_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '미트소스 가지 그라탱';
UPDATE cooking_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '캔들라이트 디너';
UPDATE cooking_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '킹크랩 찜';
UPDATE cooking_collections SET mastery_beginner_max = 60, mastery_intro_min = 60, mastery_expert_min = 180, mastery_master_min = 360 WHERE name = '황금 킹크랩';

-- 명인 crop.txt
UPDATE crop_collections SET mastery_beginner_max = 900, mastery_intro_min = 900, mastery_expert_min = 2700, mastery_master_min = 5400 WHERE name = '감자';
UPDATE crop_collections SET mastery_beginner_max = 1200, mastery_intro_min = 1200, mastery_expert_min = 3600, mastery_master_min = 7200 WHERE name = '벼';
UPDATE crop_collections SET mastery_beginner_max = 1200, mastery_intro_min = 1200, mastery_expert_min = 3600, mastery_master_min = 7200 WHERE name = '토마토';
UPDATE crop_collections SET mastery_beginner_max = 700, mastery_intro_min = 700, mastery_expert_min = 2100, mastery_master_min = 4200 WHERE name = '밀';
UPDATE crop_collections SET mastery_beginner_max = 500, mastery_intro_min = 500, mastery_expert_min = 1500, mastery_master_min = 3000 WHERE name = '양상추';
UPDATE crop_collections SET mastery_beginner_max = 1200, mastery_intro_min = 1200, mastery_expert_min = 3600, mastery_master_min = 7200 WHERE name = '파인애플';
UPDATE crop_collections SET mastery_beginner_max = 900, mastery_intro_min = 900, mastery_expert_min = 2700, mastery_master_min = 5400 WHERE name = '당근';
UPDATE crop_collections SET mastery_beginner_max = 700, mastery_intro_min = 700, mastery_expert_min = 2100, mastery_master_min = 4200 WHERE name = '딸기';
UPDATE crop_collections SET mastery_beginner_max = 500, mastery_intro_min = 500, mastery_expert_min = 1500, mastery_master_min = 3000 WHERE name = '옥수수';
UPDATE crop_collections SET mastery_beginner_max = 500, mastery_intro_min = 500, mastery_expert_min = 1500, mastery_master_min = 3000 WHERE name = '포도';
UPDATE crop_collections SET mastery_beginner_max = 700, mastery_intro_min = 700, mastery_expert_min = 2100, mastery_master_min = 4200 WHERE name = '가지';

-- 명인 flower.txt
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '데이지';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '팬지';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '꽃양귀비';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '안스리움';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '나팔꽃';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '칼라';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '카네이션';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '튤립';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '백합';
UPDATE flower_collections SET mastery_beginner_max = 50, mastery_intro_min = 50, mastery_expert_min = 100, mastery_master_min = 300 WHERE name = '장미';
